# Generated by Django 2.0 on 2018-02-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='function',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_code', models.CharField(max_length=50)),
                ('function_name', models.TextField(max_length=2000)),
                ('function_url', models.CharField(blank=True, max_length=1000)),
                ('url', models.URLField(blank=True)),
                ('function_type', models.CharField(blank=True, max_length=50)),
                ('enable_flag', models.CharField(blank=True, max_length=1)),
                ('parent_function_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function', to='login.function')),
            ],
        ),
        migrations.CreateModel(
            name='sys_role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=50)),
                ('role_name', models.TextField(max_length=2000)),
                ('enable_flag', models.CharField(blank=True, default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='sys_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('enable_flag', models.CharField(blank=True, max_length=1)),
                ('bg_admin_flag', models.CharField(max_length=1, null=True)),
                ('company_id', models.IntegerField(null=True)),
                ('employee_id', models.IntegerField(null=True)),
                ('frozen_flag', models.CharField(max_length=1, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
