# Generated by Django 2.0 on 2018-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsList',
            fields=[
                ('newsId', models.AutoField(primary_key=True, serialize=False)),
                ('newsName', models.CharField(db_index=True, max_length=200, unique=True)),
                ('newsAuthor', models.CharField(max_length=200)),
                ('newsStatus', models.CharField(max_length=200)),
                ('newsLook', models.CharField(max_length=200)),
                ('isShow', models.CharField(max_length=200)),
                ('newsTime', models.DateField(null=True)),
            ],
        ),
    ]
