# Generated by Django 2.0 on 2018-02-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180219_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='isShow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='newsAuthor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='newsLook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='newsStatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newslist',
            name='newsTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
