# Generated by Django 2.0 on 2018-03-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180318_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='last_update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_code',
            field=models.CharField(db_index=True, help_text='角色代码', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, help_text='角色名称', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
