# Generated by Django 2.0.4 on 2018-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180406_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='用户类型'),
        ),
    ]
